version: "3.9"
services:
  vaporcito:
    # image: vaporcito2
    build: ./
    hostname: my-vaporcito
    environment:
      - PUID=1000
      - PGID=1000
    # volumes:
    #   - /wherever/st-sync:/var/syncthing
    ports:
      - 8384:8384 # Web UI
      - 22000:22000/tcp # TCP file transfers
      - 22000:22000/udp # QUIC file transfers
      - 21027:21027/udp # Receive local discovery broadcasts
    restart: unless-stopped